/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nc_lib_testActivity */

#ifndef _Included_nc_lib_testActivity
#define _Included_nc_lib_testActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nc_lib_testActivity
 * Method:    TestFromJNI
 * Signature: ()Ljava/lang/String;
 */
// Do not need .h file on ndkr9?
/*JNIEXPORT jstring JNICALL Java_nc_lib_testlibActivity_TestFromJNI
  (JNIEnv *, jobject);*/

#ifdef __cplusplus
}
#endif
#endif
